echo "Puzzle 1 - Word"
python main.py puzzles/puzzle1.txt word notrace
echo "Puzzle 1 - Letter"
python main.py puzzles/puzzle1.txt letter notrace
echo "Puzzle 2 - Word"
python main.py puzzles/puzzle2.txt word notrace
echo "Puzzle 2 - Letter"
python main.py puzzles/puzzle2.txt letter notrace
echo "Puzzle 3 - Word"
python main.py puzzles/puzzle3.txt word notrace
echo "Puzzle 3 - Letter"
python main.py puzzles/puzzle3.txt letter notrace
echo "Puzzle 4 - Word"
python main.py puzzles/puzzle4.txt word notrace
echo "Puzzle 4 - Letter"
python main.py puzzles/puzzle4.txt letter notrace
echo "Puzzle 5 - Word"
python main.py puzzles/puzzle5.txt word notrace
echo "Puzzle 5 - Letter"
python main.py puzzles/puzzle5.txt letter notrace
