python main.py puzzles/puzzle1.txt word
python main.py puzzles/puzzle1.txt letter
python main.py puzzles/puzzle2.txt word
python main.py puzzles/puzzle2.txt letter
python main.py puzzles/puzzle3.txt word
python main.py puzzles/puzzle3.txt letter
python main.py puzzles/puzzle4.txt word
python main.py puzzles/puzzle4.txt letter
python main.py puzzles/puzzle5.txt word
python main.py puzzles/puzzle5.txt letter
